#! /usr/bin/bash

#echo $1 $2 $3 ' -> echo $1 $2 $3'
if [ $1 = s ] ; then
echo Running server. Please wait...
python3 manage.py runserver 
fi
if [ $1 = ? ] ; then
printf "............\n Use ./run [x]:\n m -to migrate\n s -to run server\n p -to start postgretsql server\n shell to run Django Python shell\n...........\n"
fi
if [ $1 = m ] ; then
echo Migrating. Please wait...
python3 manage.py makemigrations
python3 manage.py migrate
fi
if [ $1 = p ] ; then
echo Starting PostgreSQL serice...
sudo service postgresql start
fi
if [ $1 = shell ] ; then
echo "Starting Django Python shell. Use exit() or quit() when done."
python3 manage.py shell
fi